# Blueprint for deploying Inwit Tix on Render

# Databases are defined in their own top-level section
databases:
  - name: inwit-tix-db
    plan: free

services:
  # The main Flask web application
  - type: web
    name: inwit-tix-app
    env: python
    plan: free
    buildCommand: "./build.sh" # We will use a build script
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

