# Blueprint for deploying Inwit Tix on Render's native environment

# UPDATED: Add a 'databases' section to create a real database
databases:
  - name: inwit-tix-db
    plan: free # A free PostgreSQL instance

services:
  # The main Flask web application
  - type: web
    name: inwit-tix-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        # UPDATED: Correctly link to the database created above
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

