# Blueprint for deploying Inwit Tix on Render using Docker

databases:
  - name: inwit-tix-db
    plan: free # UPDATED: Reverted to the free plan

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: free # UPDATED: Reverted to the free plan
    healthCheckPath: /
    # Use a pre-deploy command for database initialization
    preDeployCommand: "flask db-init"
    envVars:
      - key: FLASK_APP
        value: app:app
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

