# Blueprint for deploying Inwit Tix on Render using Docker

databases:
  - name: inwit-tix-db
    region: frankfurt
    plan: free

services:
  - name: inwit-tix-app
    type: web
    region: frankfurt
    env: docker
    plan: free
    healthCheckPath: /
    # Run the database initialization command before starting the app
    initCommand: "flask db-init"
    envVars:
      # NEW: Explicitly tell Flask where to find the application object
      - key: FLASK_APP
        value: app:app
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

