# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter'
    healthCheckPath: /
    # The preDeployCommand is removed. The startup script inside the Dockerfile handles initialization.
    envVars:
      # The DATABASE_URL must be set manually in the Render dashboard environment tab
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1
