# Blueprint for deploying Inwit Tix on Render

services:
  # A PostgreSQL database for our application
  - type: postgres
    name: inwit-tix-db
    plan: free # Can be upgraded later
    # Render will automatically set the DATABASE_URL environment variable

  # The main Flask web application
  - type: web
    name: inwit-tix-app
    env: python
    plan: free # Can be upgraded later
    buildCommand: |
      pip install -r requirements.txt
      # Install system libraries required by WeasyPrint for PDF generation
      apt-get update && apt-get install -y libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure secret key
      - key: DATABASE_URL
        fromService:
          type: psql
          name: inwit-tix-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1

