# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker
# This version connects to a pre-existing database.

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter'
    healthCheckPath: /
    # The preDeployCommand has been removed. The Dockerfile's CMD and start.sh now handle initialization.
    envVars:
      # DATABASE_URL must be set manually in the Render dashboard environment tab
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1

