# Blueprint for deploying Inwit Tix on Render using Docker

databases:
  - name: inwit-tix-db
    plan: free

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    # UPDATED: Moved the database initialization back to the build command
    buildCommand: |
      pip install -r requirements.txt
      flask db-init
    envVars:
      - key: FLASK_APP
        value: app:app
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

