# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker

databases:
  - name: inwit-tix-db
    # Plan is removed to avoid legacy errors and use the existing or default plan.

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter' # Entry-level paid web service plan
    healthCheckPath: /
    # Use a pre-deploy command for database initialization on paid plans
    preDeployCommand: "flask db-init"
    envVars:
      # FLASK_APP is already set in the Dockerfile.
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads # This path is for the persistent disk
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1 # Smallest persistent disk size

