# Blueprint for deploying Inwit Tix on Render using Docker

databases:
  - name: inwit-tix-db
    plan: free

services:
  # The main Flask web application, now built from a Dockerfile
  - type: web
    name: inwit-tix-app
    plan: free
    # Tell Render to use the Docker environment
    env: docker
    # Render will automatically find and use the Dockerfile in your repository
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString

