# A simplified blueprint for a basic deployment on Render's free plan

services:
  # The main Flask web application using Render's native Python environment
  - type: web
    name: inwit-tix-app
    env: python # Reverted to native Python environment
    plan: free
    # The build command now only installs Python packages
    buildCommand: "pip install -r requirements.txt"
    # The start command remains the same
    startCommand: "gunicorn app:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_APP
        value: app:app
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: psql
          name: inwit-tix-db
          property: connectionString

  # A PostgreSQL database for our application
  - type: psql
    name: inwit-tix-db
    plan: free

