# Blueprint for deploying Inwit Tix on Render using Docker

databases:
  - name: inwit-tix-db
    plan: free

services:
  # The main Flask web application, now built from a Dockerfile
  - type: web
    name: inwit-tix-app
    plan: free
    env: docker
    healthCheckPath: /
    # Add an initCommand to create the database tables before starting
    initCommand: "flask db-init"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString

