# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker
# This version connects to a pre-existing, manually created database.

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter' # This is still a valid plan for the web service
    healthCheckPath: /
    # The preDeployCommand has been removed. Initialization will be done manually.
    envVars:
      # The DATABASE_URL must be set manually in the Render dashboard environment tab
      - key: FLASK_APP
        value: app:app
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1
