# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker

databases:
  - name: inwit-tix-db
    plan: 'starter'

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter'
    healthCheckPath: /
    # The preDeployCommand has been removed. The Dockerfile's CMD and start.sh now handle initialization.
    envVars:
      - key: FLASK_APP
        value: app:app
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1

