# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker
# This version connects to a pre-existing database.

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter'
    healthCheckPath: /
    preDeployCommand: "flask db-init"
    envVars:
      - key: FLASK_APP
        value: app:app
      # The DATABASE_URL will be set manually in the Render Dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1

