# Blueprint for deploying Inwit Tix on Render using a Paid Plan and Docker

databases:
  - name: inwit-tix-db
    plan: 'starter' # Entry-level paid database plan

services:
  - name: inwit-tix-app
    type: web
    env: docker
    plan: 'starter' # Entry-level paid web service plan
    healthCheckPath: /
    # Use a pre-deploy command for database initialization on paid plans
    # This explicit command ensures Flask can find your app
    preDeployCommand: "FLASK_APP=app:app flask db-init"
    envVars:
      - key: FLASK_APP
        value: app:app
      - key: DATABASE_URL
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /var/data/uploads # This path is for the persistent disk
    disk:
      name: uploads-disk
      mountPath: /var/data/uploads
      sizeGB: 1 # Smallest persistent disk size

