# Blueprint for deploying Inwit Tix on Render's native environment

# Define the database for your application
databases:
  - name: inwit-tix-db
    plan: starter # A paid PostgreSQL instance

# Define the services for your application
services:
  # The main Flask web application
  - type: web
    name: inwit-tix-app
    # Use the native Python environment
    env: python
    plan: starter # A paid web service instance
    # Define the command to build the application
    buildCommand: "./build.sh"
    # Define the command to start the application
    startCommand: "gunicorn app:app"
    # Define environment variables
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5"
      - key: DATABASE_URL
        # Correctly link to the database created above
        fromDatabase:
          name: inwit-tix-db
          property: connectionString
      - key: SECRET_KEY
        # Tell Render to automatically generate a secure secret key
        generateValue: true

